import React, { Suspense } from 'react';
import MovieVideos from '../../../../../components/movieVideos';
import MovieInfo, { fetchMovie } from '../../../../../components/movieInfo';
import { Metadata } from 'next';

export const generateMetaData = async ({ params: { id } }: { params: { id: string } }) => {
  const movie = await fetchMovie(id);
  return {
    title: `Movie ${movie.title}`,
    description: `Movie ${id} description`,
  };
};

export const metadata: Metadata = {
  title: 'Hey',
  description: 'Generated by create next app',
};

const Movie = async ({ params: { id } }: { params: { id: string } }) => {
  return (
    <div>
      <h1>Hello movie id {id}</h1>

      <Suspense fallback={<h1>Loading movie info</h1>}>
        <MovieInfo id={id} />
      </Suspense>

      <Suspense fallback={<h1>Loading movie videos</h1>}>
        <MovieVideos id={id} />
      </Suspense>
    </div>
  );
};

export default Movie;
