import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'Hey',
  description: 'Generated by create next app',
};
const Hey = () => {
  return (
    <div>
      <h1>Hi</h1>
    </div>
  );
};

export default Hey;
