import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App 2',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      {children} <h3>Yo</h3>
    </>
  );
}
